---
- name: Install Nginx on all servers and set hostname
  hosts: webservers
  become: yes

  vars:
    new_hostname: "your-desired-hostname"  # حطي هنا اسم الهوست اللي عايزة

  tasks:
    - name: Set hostname
      hostname:
        name: "{{ new_hostname }}"

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Replace Nginx welcome message
      copy:
        content: |
          <html>
          <head><title>Welcome Ahmed</title></head>
          <body><h1>Welcome to My Custom Page!</h1></body>
          </html>
        dest: /var/www/html/index.nginx-debian.html
        owner: root
        group: root
        mode: '0644'

    - name: Restart Nginx to apply changes
      service:
        name: nginx
        state: restarted
