---
- hosts: pxc_nodes
  become: true
  gather_facts: yes

  vars:
    wsrep_cluster_name: "my_pxc-cluster"
    cluster_nodes:
      - 11.1.1.245
      - 11.1.1.246
      - 11.1.1.247

  tasks:
    - name: Ensure MySQL config directory exists
      file:
        path: /etc/mysql/mysql.conf.d
        state: directory
        mode: "0755"

    - name: Deploy mysqld.cnf with PXC configuration
      template:
        src: wsrep.cnf.j2
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root
        mode: "0644"
        backup: yes
      notify: Restart MySQL

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
